config/routes.rb
Rails.application.routes.draw do
  root 'users#show'

  devise_for :users
  resources :users, only: [:show]
  resources :activities
  resources :groups
  resources :memberships
  resources :activity_entries, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :password, presence: true, length: { in: 7..32 }, confirmation: { case_sensitive: true }
  validates :password_confirmation, presence: true
  VALID_NAME_REGEX = /\A[a-zA-Z ,.'-]+\z/
  validates :first_name, presence: true, length: { in: 1..50 }, format: { with: VALID_NAME_REGEX, message: 'only allows letters' }
  validates :last_name, presence: true, length: { in: 1..50 }, format: { with: VALID_NAME_REGEX, message: 'only allows letters' }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }

  has_many :groups, through: :memberships
  has_many :groups, foreign_key: :creator_id, class_name: 'Group'
  has_many :memberships, foreign_key: :user_id, dependent: :destroy
  has_many :activities, foreign_key: :author_id, class_name: 'Activity'

  scope :recent_activities_all, ->(user) { user.activities.where('author_id = ? AND created_at >= ?', user.id, Date.today - 28).order(created_at: :desc) }
  scope :recent_activities7, ->(user) { user.activities.where('author_id = ? AND created_at >= ?', user.id, Date.today - 7) }
  scope :recent_activities14, ->(user) { user.activities.where('created_at BETWEEN ? AND ?', Date.today - 14, Date.today - 7) }
  scope :recent_activities21, ->(user) { user.activities.where('created_at BETWEEN ? AND ?', Date.today - 21, Date.today - 14) }
  scope :recent_activities28, ->(user) { user.activities.where('created_at BETWEEN ? AND ?', Date.today - 28, Date.today - 21) }
  scope :undiscovered_groups, ->(user) { Group.all.where('id NOT IN (?)', user.memberships.map(&:group_id)) }
  scope :joined_groups, ->(user) { Group.all.where('id IN (?)', user.memberships.map(&:group_id)) }

  def user_name
    "#{first_name} " + last_name.to_s
  end

  def user_id
    id
  end

  def author_name
    "#{first_name} " + last_name.to_s
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @my_groups = User.joined_groups(current_user)
    @recent_activities_all = User.recent_activities_all(current_user)
    @recent_activities7 = User.recent_activities7(current_user)
    @recent_activities14 = User.recent_activities14(current_user)
    @recent_activities21 = User.recent_activities21(current_user)
    @recent_activities28 = User.recent_activities28(current_user)
    @all_activities = current_user.activities.includes([:group]).order(created_at: :desc)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name
    "#{current_user.first_name} #{current_user.last_name}"
  end

  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=identicon&s=400"
    image_tag(gravatar_url, alt: user.first_name.titleize, class: 'gravatar')
  end

  def quick_stats_dots(count)
    count = 7 if count > 7
    inactive = '<i class="d-inline-block far fa-circle"></i>'
    active = '<i class="d-inline-block fas fa-circle"></i>'
    active_count = 7 - count
    printer = ''
    inactive_count = 7 - active_count
    inactive_count.times do
      printer.concat(active)
    end
    active_count.times do
      printer.concat(inactive)
    end
    printer.html_safe
  end
end

app/views/users/_all_activities.html.erb
<ul class="list-unstyled all-activities-list p-2">
  <% @all_activities.each do |activity| %>
    <li class="d-table">
      <div class='h-100 w-auto all-activities-item mb-3'>
        <p class='d-inline-block mb-0 mr-1 w-auto'><i class="<%= activity.group_icon %>"></i></p>
        <p class='d-inline-block mb-0 w-auto'><%= link_to "#{activity.name}", activity_path(activity) %> • </p>
        <p class='d-inline-block mb-0 w-auto'><%= activity.created_at.strftime('%B %e') %></p>
      </div>
    </li>
  <% end %>
</ul>

app/views/users/_group_list.html.erb
<ul class="list-unstyled my-groups-list px-1">
  <% @my_groups.each do |m| %>
    <li class="d-inline-block mb-2 mr-3">
      <div class="my-group-name mb-2 d-flex align-items-center">
        <div class="d-inline-block profile-widget-icon">
          <i class="<%= m.icon %>"></i>
        </div>
        <div class="d-inline-block mb-0 profile-widget-group-name">
          <p class="mb-0"><%= link_to "#{m.name}", group_path(m) %></p>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/users/_quickstats_dots.html.erb
<div class="quick-stats-weekly-overview w-100 d-flex">
  <div class="d-flex flex-column w-100 quick-stats-weeks quick-stats-dots px-2">
    <div class="d-flex flex-row w-100 justify-content-center">
      <p class='d-inline-block mr-2'><%= (Date.today - 7).strftime('%B %e') %></p>
      <p class="d-flex-inline justify-content-start align-items-start h-100">
        <%= quick_stats_dots(@recent_activities7.count)%>
      </p>
    </div>
    <div class="d-flex flex-row w-100 justify-content-center">
      <p class='d-inline-block mr-2'><%= (Date.today - 14).strftime('%B %e') %></p>
      <p class="d-flex-inline justify-content-start align-items-start h-100">
        <%= quick_stats_dots(@recent_activities14.count)%>
      </p>
    </div>
    <div class="d-flex flex-row w-100 justify-content-center">
      <p class='d-inline-block mr-2'><%= (Date.today - 21).strftime('%B %e') %></p>
      <p class="d-flex-inline justify-content-start align-items-start h-100">
        <%= quick_stats_dots(@recent_activities21.count)%>
      </p>
    </div>
    <div class="d-flex flex-row w-100 justify-content-center">
      <p class='d-inline-block mr-2'><%= (Date.today - 28).strftime('%B %e') %></p>
      <p class="d-flex-inline justify-content-start align-items-start h-100">
        <%= quick_stats_dots(@recent_activities28.count)%>
      </p>
    </div>
  </div>
</div>

app/views/users/_recent_activities.html.erb
<ul class="list-unstyled pt-2 w-100 mb-0 pb-0 px-1">
  <% @recent_activities_all.limit(5).each do |activity| %>
    <li>
      <div class="my-group-name">
        <div class="profile-widget-group-name mb-2">
          <p class="d-inline-block mb-0 recent-activity-name">
            <%= link_to "#{activity.name}", activity_path(activity) %>
          </p>
          <p class="d-inline-block mb-0"> • <%= activity.calories %> cals</p>
          <p class="d-inline-block mb-0"> • <%= time_converter(activity.amount) %></p>
          <p class="d-inline-block mb-0"> • <%= time_ago_in_words(activity.created_at) %> ago</p>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<main class="profile-container w-100 h-100 p-3 m-0">
  <div class="w-100 profile-top-section mx-0 px-2 d-flex flex-row">
    <aside class="profile-column d-flex flex-column justify-content-center align-items-center mr-1">
      <%= gravatar_for(current_user) %>
      <h1 class="profile-name mt-2"><%= full_name %></h1>
      <p class="profile-join">Joined on <%= current_user.created_at.strftime('%B %e %Y') %></p>
    </aside>
    <div class="d-flex flex-column main-column">
      <ul class="float-right profile-quicklinks my-0 d-flex align-items-center">
        <li class="d-inline"><%= link_to 'Recent Activities', activity_entries_path %></li>
        <li class="d-inline"><%= link_to 'Create Activity', new_activity_path %></li>
        <li class="d-inline"><%= link_to 'Create Group', new_group_path %></li>
      </ul>
      <div class="profile-quick-stats d-flex flex-row">
        <div class="profile-activity-counter d-flex justify-content-start align-items-center flex-column mr-1">
          <p class="mb-0 activity-count"><%= @recent_activities_all.count %></p>
          <p class="mt-3 font-weight-bold">Activities in the last 4 weeks</p>
          <%= render 'users/quickstats_dots' %>
        </div>
        <div class="profile-widget ml-3">
          <div>
            <div class="profile-widget-activity d-flex justify-content-start align-items-center flex-column pt-1 pr-0">
              <h2 class="mr-auto ml-3">Most Recent Activities</h2>
              <%= render 'users/recent_activities' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="profile-bottom-section w-100 mx-0 d-flex flex-row">
    <div class="profile-activities-list h-100 w-50">
      <h2 class="pl-4 pt-2 mb-1">All Activities</h2>
      <%= render 'users/all_activities' %>
    </div>
    <div class="profile-group-list h-100 w-50 px-1">
    <h2 class="pl-4 pt-2 mb-1">My Groups</h2>
      <%= render 'users/group_list' %>
    </div>
  </div>
</main>