config/routes.rb
Rails.application.routes.draw do
  root 'users#show'

  devise_for :users
  resources :users, only: [:show]
  resources :activities
  resources :groups
  resources :memberships
  resources :activity_entries, only: [:index]
end

app/models/activity_entry.rb
class ActivityEntry < ApplicationRecord
  belongs_to :activity, dependent: :destroy
  belongs_to :group
  validates :activity, presence: true
  validates :group, presence: true

  scope :recent_group_activity, ->(group) { where('group_id = ? AND created_at >= ?', group.id, Date.today - 7).count }
end

app/controllers/activity_entries_controller.rb
class ActivityEntriesController < ApplicationController
  def index
    @my_activities = current_user.activities.all.includes([:group]).order(created_at: :desc)
  end

  def new
    @activity_entry = ActivityEntry.new
  end

  def create
    @activity_entry = ActivityEntry.new(activity_entry_params)
  end

  private

  def activity_entry_params
    permit(:activity_entry).permit(:activity_id, :group_id)
  end
end

app/helpers/activity_entries_helper.rb
module ActivityEntriesHelper
end

app/views/activity_entries/_my_activities.html.erb
<div class="my-activities-list p-2">
  <ul class="list-unstyled p-0 m-0 w-100">
    <% @my_activities.each do |activity| %>
      <li>
        <div class="activity-list-item d-flex flex-row align-items-center w-100">
          <div class="d-flex align-items-center icon-title">
            <p class="mr-2 mb-0 d-flex justify-content-center align-items-center"><i class="<%= activity.group_icon %>"></i></p>
            <h2 class="activity-name d-inline-block"><%= link_to "#{activity.name}", activity_path(activity), class: 'w-auto' %></h2>
          </div>
          <div class="activity-list-delete d-flex align-items-center justify-content-center mr-3 ml-auto">
            <%= button_to 'Delete', { :controller => 'activities', action: 'destroy', :id => activity.id }, :method => :delete, data: { confirm: 'Are you sure? This action cannot be undone.' }, class: 'delete-button' %>
          </div>
          <div class="my-activities-stats">
            <p class="d-inline-block mr-1"><%= activity.calories %> cals • </p>
            <p class="d-inline-block mr-1"><%= time_converter(activity.amount) %> • </p>
            <p class="d-inline-block mr-1"><%= time_ago_in_words(activity.created_at) %> ago.</p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/activity_entries/index.html.erb
<main class="w-100 h-100 d-flex justify-content-center align-items-center p-0 m-0">
  <div class="my-activities-container d-flex justify-content-center align-items-center flex-column p-0 m-0">
    <div class='new-activity'>
      <%= link_to 'New Activity', new_activity_path %>
    </div>
    <header>
      <h1>My Activities</h1>
      <p>All your <u>most recent</u> activities</p>
    </header>
    <%= render 'activity_entries/my_activities' %>
  </div>
</main>

app/views/activity_entries/show.html.erb
<main class="w-100 h-100 d-flex justify-content-center align-items-center p-0 m-0">
  <div class="my-activities-container d-flex justify-content-center align-items-center flex-column p-0 m-0">
    <div class='new-activity'>
      <%= link_to 'New Activity', new_activity_path %>
    </div>
    <header>
      <h1>My Activities</h1>
      <p>All your <u>most recent</u> activities</p>
    </header>
    <div class="my-activities-list p-4">
      <ul class="list-unstyled p-0 m-0 w-100">
        <% @my_activities.each do |activity| %>
          <li>
            <div class="activity-list-item d-flex flex-row align-items-center w-100">
              <div class="d-flex align-items-center icon-title">
                <p class="mr-2 mb-0 d-flex justify-content-center align-items-center"><i class="<%= activity.group_icon %>"></i></p>
                <h2 class="activity-name d-inline-block"><%= link_to "#{activity.name}", activities_show_path(activity) %></h2>
              </div>
              <div class="activity-list-delete d-flex align-items-center justify-content-center mr-3 ml-auto">
                <%= button_to 'Delete', { :controller => 'activities', action: 'destroy', :id => activity.id }, :method => :delete, data: { confirm: 'Are you sure? This action cannot be undone.' }, class: 'delete-button' %>
              </div>
              <div class="my-activities-stats">
                <p class="d-inline-block mr-1"><%= activity.calories %> cals • </p>
                <p class="d-inline-block mr-1"><%= time_converter(activity.amount) %> • </p>
                <p class="d-inline-block mr-1"><%= time_ago_in_words(activity.created_at) %> ago.</p>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
      </div>
  </div>
</main>