config/routes.rb
Rails.application.routes.draw do
  root 'users#show'

  devise_for :users
  resources :users, only: [:show]
  resources :activities
  resources :groups
  resources :memberships
  resources :activity_entries, only: [:index]
end

app/views/layouts/_flash_messages.html.erb
<div class="flash-messages">
  <% if notice.present? %>
    <div class="notice px-4 py-3">
      <p class="mb-0"> <%= notice %> </p>
    </div>
  <% end %>
  <% if alert.present? %>
    <div class="alert">
      <p class="mb-0"> <%= alert %> </p>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar flex-column pr-0 position-fixed">
  <%= link_to root_path, class: 'navbar-header d-flex flex-column justify-content-center align-items-center' do %>
    <%= gravatar_for(current_user) %>
    <h3><%= full_name %></h3>
  <% end %>
  <div class="navbar-links mb-auto w-100 pl-2" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <i class="fas fa-cog"></i><%= link_to 'Account settings', user_path(current_user), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <i class="fas fa-plus"></i><%= link_to 'New Activity', new_activity_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <i class="fas fa-running"></i><%= link_to 'My Activities', activity_entries_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <i class="fas fa-users"></i><%= link_to 'My Groups', membership_path(current_user), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <i class="fas fa-sign-out-alt"></i><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoRCapstoneActivityTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main-container d-flex align-items-center justify-content-center">
      <%= render 'layouts/flash_messages' %>
      <% if current_user.nil? %>
        <%= yield %>
      <% else %>
        <%= render 'layouts/navbar' %>
        <div class="container-fluid main-card d-flex flex-row justify-content-start align-items-start signed-in-container ml-auto mr-0 px-0">
          <%= yield %>
        </div>
      <% end %>
    </div>
  </body>
</html>